const CONFIG = {
    SHEETS: {
        PRODUCTS: 'YOUR_GOOGLE_SHEET_ID_FOR_PRODUCTS',
        GALLERY: 'YOUR_GOOGLE_SHEET_ID_FOR_GALLERY',
        ABOUT: 'YOUR_GOOGLE_SHEET_ID_FOR_ABOUT'
    },
    PHONE: '9864230589'
};

